#include <stdio.h>
#include <stdlib.h>
#include <conio2.h>
int main()
{
    textattr(BLACK);
    textbackground(GREEN);
    printf("          ________________________\\             ___________\\ ");
    printf("\n         /  ___________________\\    \\           /____________\\");
    printf("\n        /   /                \\  \\    \\        /  __________   \\");
    printf("\n       /   /__________________\\  \\    \\      /  /__________ \\  |");
    printf("\n       `--'\\");
    textbackground(WHITE);
    printf("       ");
    textbackground(BLACK);
    printf("  ");
    textattr(WHITE);
    printf("__'   ");
    textbackground(WHITE);
    printf("    ");
    textattr(BLACK);
    textbackground(GREEN);
    printf("\\");
    printf("  \\   |        /");
    textbackground(WHITE);
    printf("  ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("  -    ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  \\");
    textbackground(GREEN);
    printf(" \\ |");
    printf("\n            \\");
    textbackground(WHITE);
    printf("    ");
    printf(" ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("   ");
    textbackground(WHITE);
    printf("  ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("     ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("    ");
    textbackground(GREEN);
    printf("|  \\  '       /");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("   ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("    ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  \\");
    textbackground(GREEN);
    printf(" \\|");
    printf("\n             \\");
    textattr(BLACK);
    textbackground(WHITE);
    printf("   ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("           ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("    ");
    textbackground(GREEN);
    printf("|   \\         |");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("         ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  |");
    textbackground(GREEN);
    printf("  |");
    printf("\n            \\   \\");
    textattr(WHITE);
    textbackground(BLACK);
    printf("           ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("   ");
    textbackground(GREEN);
    printf("/               \\");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  ");
    textattr(WHITE);
    textbackground(BLACK);
    printf("        ");
    textattr(BLACK);
    textbackground(WHITE);
    printf(" /");
    textbackground(GREEN);
    printf("  /");
    printf("\n             \\    \\");
    textattr(WHITE);
    textbackground(BLACK);
    printf("        ");
    textattr(BLACK);
    textbackground(WHITE);
    printf("  ");
    textbackground(GREEN);
    printf("/                               /");
    printf("\n               \\____________/                 ____      __/");
    printf("\n                          /                               \\");
    printf("\n        -                /                                 \\");
    printf("\n  __                   /                                    \\");
    printf("\n /   ");
    textbackground(LIGHTRED);
    printf("/            ");
    textbackground(GREEN);
    printf("                                          ");
    textbackground(LIGHTRED);
    printf(" |");
    textbackground(GREEN);
    printf("\n  ");
    textbackground(LIGHTRED);
    printf("                          ");
    textbackground(GREEN);
    printf("                               ");
    textbackground(LIGHTRED);
    printf(" /");
    textbackground(GREEN);
    printf("\n   ");
    textbackground(LIGHTRED);
    printf("               _________________________________________ ");
    textbackground(GREEN);
    printf("\n      ");
    textbackground(LIGHTRED);
    printf("                                                     ");
    textbackground(GREEN);
    printf("\n                 ");
    textbackground(LIGHTRED);
    printf("                                    ");
    textbackground(GREEN);
    printf("     ");
    printf("\n                    ");
    textbackground(LIGHTRED);
    printf("                            ");
    textbackground(GREEN);
    printf("      ");
    printf("\n                                                     ");
    printf("\n                                        ");
    printf("\n    ");
    gotoxy(16,25);
    textattr(WHITE);
    printf("\"PEPE THE FROG DEPRESSIVO\"");
    gotoxy(18,26);
    printf("By Weber, Gabriel");
textattr(BLACK);
textbackground(BLACK);

}
